version: "3"
services:
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    env_file:
      - .env
#    depends_on:
#      db:
#        condition: service_healthy
#        restart: true
#  db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=my_db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
#      interval: 2s
#      retries: 10
#volumes:
#  postgres_data: